INHERIT: mkdocs-base.yaml

site_name: "Dynatrace Enablement Lab: AWS Immersion Day"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace-wwse/enablement-aws-immersion-day"
nav:
  - "Welcome": index.md
  - "1. AWS & Dynatrace - Better Together": 1-aws-better-together.md
  - "2. AWS Lab 0 - Introduction and Setup": 2-aws-lab0-immersion-day.md
  - "3. AWS Lab 1 - OneAgent Observability": 3-aws-lab1.md
  - "4. AWS Lab 3 - SLOs": 4-aws-lab3.md
  - "5. AWS Lab 4 - AWS CloudWatch Integration": 5-aws-lab4-role.md
  - "6. AWS Lab 5 - Davis AI": 6-aws-lab5-davis-mono.md
  - "7. AWS Lab 6 - Dynatrace Operator for Kubernetes": 7-aws-lab6.md
  - "8. AWS Lab 7 - Modernization with Kubernetes": 8-aws-lab7.md
  - "9. AWS Lab 8 - Kubernetes Events": 9-aws-lab8-k8-events.md
  - "10. AWS Lab  9 - Davis AI for Kubernetes": 10-aws-lab9-davis-k8.md
  - "11. AWS Lab 10 - Application Security": 11-aws-lab10-appsec.md
  - "12. AWS Lab 11 - Modernization with AWS Serverless Lambda": 12-aws-lab11-serverless.md
  - "13. AWS Lab 12 - Serverless Observability with Dynatrace": 13-aws-lab12-serverless-observability.md

extra:
  rum_snippet: ""  # TODO: paste this repo's Dynatrace RUM snippet before go-live
